#!/usr/bin/env bash
CUR_DIR="$(pwd)"
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ -d "node_modules/centrifuge" ]; then
    cd node_modules/centrifuge
    git pull
else
    git clone https://github.com/centrifugal/centrifuge.git -b master node_modules/centrifuge
fi
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
./node_modules/.bin/pbjs ./node_modules/centrifuge/misc/proto/client.proto -t static-module -o ./src/Proto.js
./node_modules/.bin/pbts -o ./src/Proto.d.ts ./src/Proto.js
cd "$CUR_DIR"
